
PKG_DIR :=org/apache/log4j/performance
DEPTH   :=../../../..
JSOURCES:=NOPWriter.java\
	NotLogging.java\
	Logging.java\
	NullAppender.java\
	ListVsVector.java\
	SystemTime.java\
	NewVsSetLen.java\

SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc




