
PKG_DIR :=org/apache/log4j/net/test
DEPTH   :=../../../../..
JSOURCES:=SyslogMin.java SocketMin.java Loop.java\
	SMTPMin.java


SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc






