 
PKG_DIR :=org/apache/log4j/xml/test
DEPTH   :=../../../../..
JSOURCES:=DOMTest.java DisableOverrideTest.java \
	TPriority.java\
	TCategory.java\
	SubClassTest.java\

SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc






