
PKG_DIR :=org/apache/log4j/config
DEPTH   :=../../../../../..
JSOURCES:=PropertyGetter.java\
          PropertyPrinter.java\
          PropertySetter.java\
          PropertySetterException.java\

SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc






