
PKG_DIR :=org/log4j/spi
DEPTH   :=../../..
JSOURCES:=OptionHandler.java\
	AppenderAttachable.java\
	LoggingEvent.java\
	LocationInfo.java\
	RootCategory.java\
	Filter.java\
        ErrorHandler.java\
	ErrorCode.java\
	CategoryFactory.java\
	Configurator.java\

#ifdef FULL
#
#endif


SUBDIRS := 

# include master-rule file
include $(DEPTH)/make/make.inc






