
PKG_DIR :=org/apache/log4j/spi
DEPTH   :=../../../../../..
JSOURCES:=OptionHandler.java\
	AppenderAttachable.java\
	LoggingEvent.java\
	LocationInfo.java\
	RootCategory.java\
	Filter.java\
        ErrorHandler.java\
	ErrorCode.java\
	Configurator.java\
        ThrowableInformation.java\
	TriggeringEventEvaluator.java\
        HierarchyEventListener.java\

#        LoggerRepository.java\
#        DefaultRepositorySelector.java\
#        LoggerFactory.java\

SUBDIRS := 

# include master-rule file
include $(DEPTH)/make/make.inc






