
PKG_DIR :=org/apache/log4j/or
DEPTH   :=../../../..
JSOURCES:= ObjectRenderer.java\
	RendererMap.java\
	DefaultRenderer.java\
	ThreadGroupRenderer.java\
	MessageRenderer.java\


#ifdef FULL
#
#endif


SUBDIRS := 

# include master-rule file
include $(DEPTH)/make/make.inc






