
PKG_DIR :=org/apache/log4j/or
DEPTH   :=../../../../../..
JSOURCES:= DefaultRenderer.java\
  ObjectRenderer.java\
  RendererMap.java\
  ThreadGroupRenderer.java\


#ifdef FULL
#
#endif


SUBDIRS := jms sax

# include master-rule file
include $(DEPTH)/make/make.inc






