
PKG_DIR :=org/apache/log4j/net
DEPTH   :=../../../../../..
JSOURCES:=SyslogAppender.java\
	JMSAppender.java\
	JMSSink.java\
	SimpleSocketServer.java\
	SocketAppender.java\
	SMTPAppender.java\
	SocketNode.java\
        TelnetAppender.java\
#	SocketServer.java\


SUBDIRS :=test

# include master-rule file
include $(DEPTH)/make/make.inc






