
PKG_DIR :=org/log4j/net
DEPTH   :=../../..
JSOURCES:=SyslogAppender.java\
	SocketServer.java\
	SocketAppender.java\
	SMTPAppender.java\
	SocketNode.java\
	SyslogTracerPrintWriter.java\

SUBDIRS :=test

# include master-rule file
include $(DEPTH)/make/make.inc






