
PKG_DIR :=org/apache/log4j/net
DEPTH   :=../../../..
JSOURCES:=SyslogAppender.java\
	JMSAppender.java\
	JMSSink.java\
	SocketServer.java\
	SimpleSocketServer.java\
	SocketAppender.java\
	SMTPAppender.java\
	SocketNode.java\
	SyslogTracerPrintWriter.java\


SUBDIRS :=test

# include master-rule file
include $(DEPTH)/make/make.inc






