
PKG_DIR :=org/apache/log4j/xml
DEPTH   :=../../../../../..
JSOURCES:=DOMConfigurator.java\
	XMLLayout.java\
        SAXErrorHandler.java\

SUBDIRS := examples test

# include master-rule file
include $(DEPTH)/make/make.inc






