
PKG_DIR :=org/log4j/examples
DEPTH   :=../../..
JSOURCES:=SortAlgo.java Sort.java Trivial.java NumberCruncher.java\
	NumberCruncherServer.java\
	NumberCruncherClient.java\
	MyPatternParser.java\
	MyPatternLayout.java\
	MyCategory.java\
	MyCategoryFactory.java\


JRMI:=NumberCruncherServer.java

SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc







