
PKG_DIR :=org/apache/log4j/xml/examples
DEPTH   :=../../../../..
JSOURCES:=ReportParserError.java XMLSample.java XPriority.java\
	XCategory.java XTest.java 




SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc






