
PKG_DIR :=org/apache/log4j/varia
DEPTH   :=../../../..
JSOURCES:=ExternallyRolledFileAppender.java\
	  ResilientFileAppender.java\
	  Roller.java\
	  DenyAllFilter.java\
	  StringMatchFilter.java\
	  PriorityMatchFilter.java\

SUBDIRS :=test

# include master-rule file
include $(DEPTH)/make/make.inc






