
PKG_DIR :=org/apache/log4j/varia
DEPTH   :=../../../../../..
JSOURCES:=ExternallyRolledFileAppender.java\
	  Roller.java\
	  DenyAllFilter.java\
	  StringMatchFilter.java\
	  LevelMatchFilter.java\
	  PriorityRangeFilter.java\
	  PriorityMatchFilter.java\
          ReloadingPropertyConfigurator.java\

SUBDIRS :=test

# include master-rule file
include $(DEPTH)/make/make.inc






