#!/bin/bash

# A regression test to check extension support in DOMConfigurator and elsewhere

# Read the .functions file
. .functions

# If set, allows to skip tests 
declare -i start=$1
echo "start=$start TEMP=$TEMP OUTPUT=$OUTPUT"

function testExtSupport {
 configFile=$1
 
 echo -n "Extension support test $TEST - "
 java org.apache.log4j.xml.test.XTest $configFile

 check witness/ext.$TEST $OUTPUT; echo "OK."
}


echo "-- $OUTPUT"

declare -i TEST

TEST=1
if [ $TEST -ge $start ]; then
  testExtSupport xml/ext$TEST.xml
fi