#!/bin/bash

# Read the .functions file
. .functions

# If set, allows to skip tests 
declare -i start=$1

# ==================================================
function testGetOptions {
 echo -n "OptionHandler.getOption() test $TEST - "

 if [ -e $TEMP ]; then
   #echo "Deleting $TEMP."
   rm $TEMP
   touch $TEMP
 fi

 java $1 org.apache.log4j.test.PrintProperties > $TEMP

 check witness/getOptions.$TEST $TEMP; echo "OK."
}
# ==================================================


declare -i TEST

LCF=log4j.properties

function createProperties {
  echo -n "" > $LCF
  #if [ -n "$1" ]; then
  #  lecho "log4j.configurator=$1"
  #fi
  lecho "log4j.appender.A1=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A1.File=$TEMP"
  lecho "log4j.appender.A1.Append=false"
  lecho "log4j.appender.A1.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.A1.layout.ConversionPattern=%m%n"
  lecho "log4j.rootCategory=DEBUG, A1"
  lecho "log4j.category.org.apache.log4j=INFO, A1"
}

createProperties

TEST=1
if [ $TEST -ge $start ]; then
  testGetOptions
fi

rm $LCF
