 
PKG_DIR :=org/apache/log4j/test
DEPTH   :=../../../..
JSOURCES:= Shallow.java\
 Hello.java\
 StressNDC.java\
 StressAsyncAppender.java\
 Min.java Base64.java\
 ShippedCodeFlagTest.java\
 ConfigurationFileParsing.java\
 MultipleAppenders.java\
 PatternTest.java\
 ROFile.java\
 L7D.java\
 Finalize.java\
 DefaultInit.java\
 CategoryWrapper.java\
 ShortSocketServer.java\
 DelayedLoop.java\
 SysoutConfigurator.java\
 UnitTestOR.java\
 UnitTestCategory.java\
 UnitTestCyclicBuffer.java\
 UnitTestBoundedFIFO.java\
 UnitTestVarSubst.java\

SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc



