 
PKG_DIR :=org/apache/log4j/test
DEPTH   :=../../../../../..
JSOURCES:= Shallow.java\
 Hello.java\
 StressNDC.java\
 StressAsyncAppender.java\
 Min.java Base64.java\
 ShippedCodeFlagTest.java\
 ConfigurationFileParsing.java\
 MultipleAppenders.java\
 PatternTest.java\
 ROFile.java\
 L7D.java\
 AsyncAppenderTest.java\
 Finalize.java\
 DefaultInit.java\
 CategoryWrapper.java\
 ShortSocketServer.java\
 DelayedLoop.java\
 SysoutConfigurator.java\
 UnitTestCategory.java\
 UnitTestCyclicBuffer.java\
 UnitTestOR.java\
 UnitTestBoundedFIFO.java\
 UnitTestOptionConverter.java\
 SocketAppenderTest.java\
 PrintProperties.java\
 CustomCategoryTest.java\
 FQCNTest.java\

ifdef $(ISJDK1)
  JSOURCES:=$(JSOURCES)  UnitTestOR.java
endif

SUBDIRS :=

# include master-rule file
include $(DEPTH)/make/make.inc



