#!/bin/bash

# Read the .functions file
. .functions

# If set, allows to skip tests 
declare -i start=$1


declare -i TEST

function testSubclassing {
 
 echo -n "Subclassing test $TEST - "
 java org.apache.log4j.examples.MyCategory $LCF
 check witness/mycat.$TEST $TEMP; echo "OK."
}


TEST=1
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, A1" > $LCF
  lecho "log4j.appender.A1=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A1.File=$TEMP"
  lecho "log4j.appender.A1.Append=false"
  lecho "log4j.appender.A1.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.A1.layout.ConversionPattern=%c %p - %m%n"  
  testSubclassing
fi

rm $TEMP > /dev/null
TEST=2
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, A1" > $LCF
  lecho "log4j.appender.A1=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A1.File=$TEMP"
  lecho "log4j.appender.A1.Append=false"
  lecho "log4j.appender.A1.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.A1.layout.ConversionPattern=%c %p - %m%n"  
  lecho "log4j.category.some.cat=DEBUG"  
  testSubclassing
fi

rm $TEMP > /dev/null
TEST=3
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, A1" > $LCF
  lecho "log4j.appender.A1=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A1.File=$TEMP"
  lecho "log4j.appender.A1.Append=false"
  lecho "log4j.appender.A1.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.A1.layout.ConversionPattern=%c %p - %m%n"  
  lecho "log4j.category.some.cat=DEBUG"  
  lecho "log4j.categoryFactory=org.apache.log4j.examples.MyCategoryFactory"  
  testSubclassing
fi
