#!/bin/bash

# A regression test to check the PatternLayout code.

# Read the .functions file
. .functions

# If set, allows to skip tests 
declare -i start=$1
echo "start=$start TEMP=$TEMP OUTPUT=$OUTPUT"

function testPattern {
 layout=$1
 
 echo -n "Pattern test $TEST - "
 java org.apache.log4j.test.PatternTest $LCF
 #java -Dlog4j.configDebug org.apache.log4j.test.PatternTest $LCF
 $PERL filter.pl $TEMP $OUTPUT PatternTest $layout
 if [ $? != 0 ]; then
  echo "The output is not in expected format. See the file [$OUTPUT]."
  exit 1   
fi


 check witness/pattern.$TEST $OUTPUT; echo "OK."
}



setPERL

declare -i TEST

TEST=1
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%-5p - %m%n"  
  testPattern LINE_NUMBER
fi

TEST=2
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append= false "
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout  "
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %.16c - %m%n"  
  testPattern ISO8601
fi

TEST=3
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender  "
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout  "
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} [%t] %-5p %.16c - %m%n"  
  testPattern ISO8601
fi

TEST=4
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender "
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false "
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%d{DATE} [%t] %-5p %.16c - %m%n"  
  testPattern DATE
fi

TEST=5
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss,SSS} [%t] %-5p %.16c - %m%n"  
  testPattern DATE
fi

TEST=6
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%d{ABSOLUTE} [%t] %-5p %.16c - %m%n"  
  testPattern ABSOLUTE
fi

TEST=7
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP "
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%d{HH:mm:ss,SSS} [%t] %-5p %.16c - %m%n"  
  testPattern ABSOLUTE
fi

TEST=8
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%r [%t] %-5p %.16c - %m%n" 
  testPattern RELATIVE
fi

TEST=9
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP "
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=[%t] %-5p %.16c : %m%n" 
  testPattern LINE_NUMBER
fi

TEST=10
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File= $TEMP "
  lecho "log4j.appender.testAppender.Append= false "
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout "
  lecho "log4j.appender.testAppender.layout.ConversionPattern=[%t] %-5p %l: %m%n" 
  testPattern NONE
fi

TEST=11
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%-5p [%t] %c{2}: %m%n" 
  testPattern NONE
fi

TEST=12
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=$TEMP"
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=[%t] %-5p %C.%M(%F:%L): %m%n" 
  testPattern NONE
fi

TEST=13
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=  $TEMP "
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=[%t] %-5p %C{3}.%M(%F:%L): %m%n" 
  testPattern NONE
fi

TEST=14
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=DEBUG, testAppender" > $LCF
  lecho "log4j.appender.testAppender=org.apache.log4j.FileAppender"
  lecho "log4j.appender.testAppender.File=       $TEMP   "
  lecho "log4j.appender.testAppender.Append=false"
  lecho "log4j.appender.testAppender.layout=org.apache.log4j.examples.MyPatternLayout"
  lecho "log4j.appender.testAppender.layout.ConversionPattern=%5p %-4# - %m%n" 
  testPattern NONE
fi
