#!/bin/bash
	
# Read the .functions file
. .functions

# If set, allows to skip tests 
declare -i start=$1

WITNESS=witness/shippedCodeFlagTest

function testSCF {
  type=$1
  d=$2
  echo -n "ShippedCodeFlagTest $TEST "
  java $d org.apache.log4j.test.ShippedCodeFlagTest $type > $OUTPUT
  check $WITNESS.$TEST $OUTPUT; echo " - OK."  
}

TEST=1
if [ $TEST -ge $start ]; then
  testSCF basic
fi

TEST=2
if [ $TEST -ge $start ]; then
  testSCF basic -Dlog4j.disableOverride
fi

TEST=3
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=System.out"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi


TEST=4
if [ $TEST -ge $start ]; then
  echo "log4j.disableOverride" > $LCF
  lecho "log4j.rootCategory=,A"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=System.out"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi
