#!/bin/bash
	
# Read the .functions file
. .functions

# If set, allows to skip tests 
declare -i start=$1

WITNESS=witness/thresholdFlagTest

function testSCF {
  file=$1
  deleteFile $TEMP
  echo -n "ThresholdFlagTest $TEST "
  java org.apache.log4j.test.ThresholdFlagTest $file
  check $WITNESS.$TEST $TEMP; echo " - OK."  
}


TEST=1
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=OFF"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi

TEST=2
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=FATAL"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi

TEST=3
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=ERROR"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi

TEST=4
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=WARN"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi

TEST=5
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=INFO"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi

TEST=6
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=DEBUG"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi


TEST=7
if [ $TEST -ge $start ]; then
  echo "log4j.rootCategory=,A" > $LCF
  lecho "log4j.threshold=ALL"
  lecho "log4j.appender.A=org.apache.log4j.FileAppender"
  lecho "log4j.appender.A.File=$TEMP"
  lecho "log4j.appender.A.layout=org.apache.log4j.PatternLayout"
  lecho "log4j.appender.A.layout.ConversionPattern=%p [%t] %c{2} = %m%n"    
  testSCF $LCF 
fi



