
PKG_DIR :=org/apache/log4j/helpers
DEPTH   :=../../../..
JSOURCES:=LogLog.java\
	AppenderAttachableImpl.java\
	TracerPrintWriter.java\
	SyslogWriter.java \
	QuietWriter.java \
	CountingQuietWriter.java\
	 SyslogQuietWriter.java\
	OptionConverter.java\
	DateLayout.java\
	RelativeTimeDateFormat.java\
	AbsoluteTimeDateFormat.java\
	DateTimeDateFormat.java\
	ISO8601DateFormat.java\
	PatternConverter.java\
	PatternParser.java\
	OnlyOnceErrorHandler.java\
	CyclicBuffer.java\
	BoundedFIFO.java\
	FileWatchdog.java\
	Loader.java\

SUBDIRS := 

# include master-rule file
include $(DEPTH)/make/make.inc






