
PKG_DIR :=org/apache/log4j/jmx
DEPTH   :=../../../../../..
JSOURCES:=AbstractDynamicMBean.java\
  Agent.java\
  AppenderDynamicMBean.java\
  HierarchyDynamicMBean.java\
  LayoutDynamicMBean.java\
  LoggerDynamicMBean.java\
  MethodUnion.java\



# include master-rule file
include $(DEPTH)/make/make.inc






