name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  Test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [8, 11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Set up Java 8
      id: setup-java-8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Set up Java ${{ matrix.jdk }}
      if: ${{ matrix.jdk != '8' }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Compile
      # download dependencies, etc, so test log looks better
      run: mvn -B --toolchains .github/workflows/toolchains.xml compile
      env:
        JAVA_HOME_8: ${{ steps.setup-java-8.outputs.path }}
    - name: Test
      run: mvn -B --toolchains .github/workflows/toolchains.xml verify
      env:
        JAVA_HOME_8: ${{ steps.setup-java-8.outputs.path }}
