name: Java CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]
        java: [7, 7.0.232, 8, 8.0.192]
      fail-fast: false
      max-parallel: 3          
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test with Maven
      run: mvn test -B --file pom.xml
